### ISSUE TITLE
Why don't you use Livepeer for video transcoding?

### ISSUE THREAD

**Issue by watchcoin** [dtube/production#10] opened 2018-03-06 19:30 UTC
Guys, I see that you're having some problems with doing the video transcoding.

Why exactly aren't you using Livepeer's decentralised network for transcoding, to get recordings:

8K / 4K / 1080p / 720p / 480p / 360p / 144p everything you need, and everything you can do with ffmpeg.

You can stream the content to them, and they will stream back in these formats.

Maybe they might even stream directly into IPFS for you... I don't know if they built that bit yet.

Livepeer is decentralised on Ethereum. Talk to them in gitter.

Seriously - these guys are trying to help exactly people like you.

**Comment by skzap** [comment] 2018-03-18 18:01
Duplicate of https://github.com/dtube/production/issues/7

**Closed as completed by skzap** 2018-03-18 18:01 UTC
Labels: duplicate

**Comment by chrishobcroft** [comment] 2018-04-01 15:06
This isn't a duplicate.

There are 2 opportunities here for DTube:

1. Use Livepeer to transcode "deadstreams" (i.e. recorded content uploaded to DTube and stored in IPFS) into different resolutions 720p 480p 360p 144p etc. That is what is suggested in this issue - to stream content to Livepeer during the upload process, and store the outputted content into IPFS.

2. Use Livepeer as a mechanism for livestreaming, to allow users to livestream on d.tube and for their viewers to watch live. Details of how to get set up to broadcast on Livepeer are here: https://github.com/livepeer/wiki/wiki/How-to:-set-up-a-broadcasting-node-using-Livepeer-and-OBS

These are very different opportunities, but are both served by Livepeer's decentralised video streaming platform.
